# dvc.yaml
stages:
  data_ingestion:
    cmd: python src/Insurance/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Insurance/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/complete_raw_data
      - artifacts/data_ingestion/train_data
      - artifacts/data_ingestion/test_data

  data_transformation:
    cmd: python src/Insurance/pipeline/stage_02_data_transformation.py
    deps:
      - src/Insurance/pipeline/stage_02_data_transformation.py
      - artifacts/data_ingestion/complete_raw_data
      - artifacts/data_ingestion/train_data
      - artifacts/data_ingestion/test_data
    outs:
      - artifacts/data_transformation/train_data


  model_training:
    cmd: python src/Insurance/pipeline/stage_03_model_training.py
    deps:
      - artifacts/data_transformation/train_data
      - src/Insurance/pipeline/stage_03_model_training.py
      - artifacts/data_transformation/test_data
    outs:
      - artifacts/model_training/parameter_dir
    
     